spring:
  redis:
    database: 1
    host: 192.168.194.132
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 5
        max-wait: 5000

  datasource:
      url: jdbc:mysql://192.168.194.132:3306/mydb
      username: root
      password: 991103Lxy..
      driver-class-name: com.mysql.cj.jdbc.Driver



